# Generated by Django 6.0.3 on 2026-03-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_cartmodel_pimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='pdesc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
