# Generated by Django 6.0.3 on 2026-03-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_cartmodel_pdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartmodel',
            name='pdesc',
        ),
    ]
